# подик для кубика 

apiVersion: v1
kind: Pod
metadata:
  name: busybox-pod
  labels:
    name: busybox 
spec:
  containers:
  - name: busybox-container
    image: busybox:latest
    command: ["sleep", "infinity"]
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
      requests:
        memory: "64Mi"
        cpu: "250m"
    ports:
      - containerPort: 80
